operations:
  constants:
    cron:
      us: "* 0/1 * * * ? *"
      can: "* 0/1 * * * ? *"
    source: "EnT"
    target: "Siebel"
    country:
      us: "US"
      canada: "Canada"
    errorType:
      badRequest: "APIKIT:BAD_REQUEST"
      notFound: "APIKIT:NOT_FOUND"
      methodNotAllowed: "APIKIT:METHOD_NOT_ALLOWED"
      notAcceptable: "APIKIT:NOT_ACCEPTABLE"
      unsupportedMediaType: "APIKIT:UNSUPPORTED_MEDIA_TYPE"
      notImplemented: "APIKIT:NOT_IMPLEMENTED"
      gatewayTimeout: "HTTP:GATEWAY_TIMEOUT"

    errorCode:
      badRequest: "400"
      notFound: "404"
      methodNotAllowed: "405"
      notAcceptable: "500"
      unsupportedMediaType: "415"
      notImplemented: "501"
      internalServerError: "500"
    response:
      code:
        success: "200"
    status:
      success: "success"
      error: "error"
http:
  listener:
    port: "8092"
  request:
    basepath: "/dev/sapi/ent-orders-siebel/v1"
    sbasepath: "/dev/sapi/ent-orders-salesforce/v1"
    headers:
      siebel:
        client:
          id: "2666b1bf9bed4ecdb3d3e6871b217a05"
          secret: "d4cf6CdC5A3040bbB121A1Ee979bBAB0"
      salesforce:
        client:
          id: "64a71b2c1e6c4e4e8c4eb486f593d24b"
          secret: "b0566F426c6F4D74BBDb915BA9D70A5E"
x-origination-code: "Siebel"
x-implementation: "ENT Orders"
Content-Type: "application/json"
 
    
    
